server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.230.188
logging:
  level:
    com.atguigu: debug
auth:
  jwt:
    publicKeyPath: D:\\project-0615\\tem\\rsa.pub
    cookieName: GMALL_TOKEN


